#!/bin/bash

set -ex;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $KEYCLOAK_DATABASE_USER WITH PASSWORD '$KEYCLOAK_DATABASE_PASSWORD';
    CREATE DATABASE $KEYCLOAK_DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DATABASE_NAME TO $KEYCLOAK_DATABASE_USER;
EOSQL