version: '3.8'
# define networks
networks:
  custom:
    name: custom
# define services
services:
  # PostgreSQL as main database
  pgsql:
    image: postgres:11.18-alpine
    container_name: pgsql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=postgres"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - custom
    env_file:
      - .env.prod
    volumes:
      - ./pgsql/data:/var/postgresql/data
      - ./pgsql/initdb.d:/docker-entrypoint-initdb.d/
  # Keycloack as single-sign on
  keycloak:
    image: bitnami/keycloak
    container_name: keycloak
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - custom
    depends_on:
      pgsql:
        condition: service_healthy
    links:
      - pgsql:postgresql
    env_file:
      - .env.prod
  # Nginx as reserved proxy
  nginx:
    image: hieupth/nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - custom
    ports:
      - 80:80
      - 443:443
    depends_on:
      keycloak:
        condition: service_healthy
    links:
      - keycloak:keycloak
    env_file:
      - .env.prod
    volumes:
      - ./ssl/certs:/certs:ro
      - ./nginx/http.conf.template:/etc/nginx/templates/conf.d/http.conf.template:ro
      - ./nginx/keycloak.conf.template:/etc/nginx/templates/sites/keycloak.conf.template:ro