version: '3.8'
# define networks
networks:
  custom:
    name: custom
# define services
services:
  # PostgreSQL as main database
  pgsql:
    image: postgres:11.18-alpine
    container_name: pgsql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - custom
    env_file:
      - .env.prod
    volumes:
      - ./pgsql/data:/var/postgresql/data
      - ./pgsql/initdb.d:/var/docker-entrypoint-initdb.d
  # Keycloack as single-sign on
  keycloak:
    image: bitnami/keycloak
    container_name: keycloak
    restart: unless-stopped
    networks:
      - custom
    depends_on:
      - pgsql
    links:
      - pgsql:postgresql
    env_file:
      - .env.prod